[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "cliche"
version = "0.10.124"
description = "A minimalistic CLI wrapper out to be the best"
readme = "README.md"
license = {text = "MIT"}
authors = [
    {name = "Pascal van Kooten", email = "kootenpv@gmail.com"}
]
requires-python = ">=3.10"
dependencies = [
    "ipdb==0.13.13"
]
classifiers = [
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Intended Audience :: Customer Service",
    "Intended Audience :: System Administrators",
    "Operating System :: Microsoft",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: Unix",
    "Operating System :: POSIX",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.4",
    "Programming Language :: Python :: 3.5",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Topic :: Software Development",
    "Topic :: Software Development :: Build Tools",
    "Topic :: Software Development :: Debuggers",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: System :: Software Distribution",
    "Topic :: System :: Systems Administration",
    "Topic :: Utilities",
]

[project.urls]
Homepage = "https://github.com/kootenpv/cliche"

[project.scripts]
cliche = "cliche.__init__:main"

[tool.setuptools]
packages = ["cliche"]
include-package-data = true
zip-safe = false
platforms = ["any"]

[tool.setuptools.package-data]
"*" = ["*"]